// ===== AnnadathaBazar â€” Sample Data =====
// Realistic Indian farming context

const STATES_DISTRICTS = {
  "Telangana": ["Warangal", "Karimnagar", "Khammam", "Nalgonda", "Adilabad"],
  "Maharashtra": ["Nashik", "Pune", "Nagpur", "Aurangabad", "Solapur"],
  "Karnataka": ["Mysuru", "Belagavi", "Hubballi", "Mandya", "Tumakuru"],
  "Punjab": ["Ludhiana", "Amritsar", "Patiala", "Bathinda", "Jalandhar"],
  "Uttar Pradesh": ["Meerut", "Agra", "Lucknow", "Varanasi", "Kanpur"],
  "Gujarat": ["Rajkot", "Surat", "Vadodara", "Anand", "Bhuj"],
};

const CROPS = [
  { id: "rice", name: "Rice", hi: "à¤§à¤¾à¤¨", emoji: "ðŸŒ¾", color: "#C5D8A8" },
  { id: "wheat", name: "Wheat", hi: "à¤—à¥‡à¤¹à¥‚à¤", emoji: "ðŸŒ¾", color: "#E5C879" },
  { id: "cotton", name: "Cotton", hi: "à¤•à¤ªà¤¾à¤¸", emoji: "ðŸŒ¿", color: "#EFE8D9" },
  { id: "tomato", name: "Tomato", hi: "à¤Ÿà¤®à¤¾à¤Ÿà¤°", emoji: "ðŸ…", color: "#D77A6E" },
  { id: "onion", name: "Onion", hi: "à¤ªà¥à¤¯à¤¾à¤œ", emoji: "ðŸ§…", color: "#C99B6F" },
  { id: "chili", name: "Chili", hi: "à¤®à¤¿à¤°à¥à¤š", emoji: "ðŸŒ¶", color: "#C45A3A" },
  { id: "turmeric", name: "Turmeric", hi: "à¤¹à¤²à¥à¤¦à¥€", emoji: "ðŸŒ±", color: "#D9A841" },
  { id: "sugarcane", name: "Sugarcane", hi: "à¤—à¤¨à¥à¤¨à¤¾", emoji: "ðŸŒ¿", color: "#A8B97A" },
  { id: "soybean", name: "Soybean", hi: "à¤¸à¥‹à¤¯à¤¾à¤¬à¥€à¤¨", emoji: "ðŸ«˜", color: "#B8A572" },
  { id: "groundnut", name: "Groundnut", hi: "à¤®à¥‚à¤à¤—à¤«à¤²à¥€", emoji: "ðŸ¥œ", color: "#B89067" },
  { id: "maize", name: "Maize", hi: "à¤®à¤•à¥à¤•à¤¾", emoji: "ðŸŒ½", color: "#DDB54B" },
  { id: "potato", name: "Potato", hi: "à¤†à¤²à¥‚", emoji: "ðŸ¥”", color: "#C9A07A" },
];

const CATEGORIES = [
  { id: "crop", label: "Crops", hi: "à¤«à¤¼à¤¸à¤²", icon: "wheat" },
  { id: "livestock", label: "Livestock", hi: "à¤ªà¤¶à¥à¤§à¤¨", icon: "leaf" },
  { id: "service", label: "Services", hi: "à¤¸à¥‡à¤µà¤¾", icon: "tool" },
  { id: "equipment", label: "Equipment", hi: "à¤‰à¤ªà¤•à¤°à¤£", icon: "tractor" },
  { id: "input", label: "Inputs", hi: "à¤¬à¥€à¤œ/à¤–à¤¾à¤¦", icon: "seed" },
  { id: "land", label: "Land", hi: "à¤œà¤¼à¤®à¥€à¤¨", icon: "field" },
  { id: "other", label: "Other", hi: "à¤…à¤¨à¥à¤¯", icon: "more" },
];

// Sell-a-thing categories surfaced in "Post a Listing"
const LISTING_CATEGORIES = [
  { id: "crop",      label: "Crops",       hi: "à¤«à¤¼à¤¸à¤²",      icon: "wheat" },
  { id: "seeds",     label: "Seeds",       hi: "à¤¬à¥€à¤œ",       icon: "seed" },
  { id: "fertilizer",label: "Fertilizer",  hi: "à¤–à¤¾à¤¦",       icon: "leaf" },
  { id: "pesticide", label: "Pesticides",  hi: "à¤•à¥€à¤Ÿà¤¨à¤¾à¤¶à¤•",   icon: "drop" },
  { id: "livestock", label: "Livestock",   hi: "à¤ªà¤¶à¥à¤§à¤¨",     icon: "leaf" },
  { id: "land",      label: "Land",        hi: "à¤œà¤¼à¤®à¥€à¤¨",     icon: "field" },
  { id: "equipment", label: "Equipment",   hi: "à¤‰à¤ªà¤•à¤°à¤£",     icon: "tractor" },
  { id: "other",     label: "Other",       hi: "à¤…à¤¨à¥à¤¯",      icon: "more" },
];

// Service categories surfaced in "Post a Service" â€” automatic grouping
const SERVICE_TYPES = [
  { id: "rental",      label: "Equipment Rental",  hi: "à¤•à¤¿à¤°à¤¾à¤¯à¥‡ à¤ªà¤° à¤®à¤¶à¥€à¤¨", icon: "tractor",
    hint: "Tractor, water pump, rotavatorâ€¦" },
  { id: "harvesting",  label: "Harvesting",        hi: "à¤•à¤Ÿà¤¾à¤ˆ à¤¸à¥‡à¤µà¤¾",      icon: "wheat",
    hint: "Combine harvester, threshing" },
  { id: "spraying",    label: "Spraying / Drone",  hi: "à¤›à¤¿à¤¡à¤¼à¤•à¤¾à¤µ / à¤¡à¥à¤°à¥‹à¤¨", icon: "drop",
    hint: "Pesticide & fertilizer spraying" },
  { id: "veterinary",  label: "Veterinary",        hi: "à¤ªà¤¶à¥ à¤šà¤¿à¤•à¤¿à¤¤à¥à¤¸à¤¾",    icon: "leaf",
    hint: "AI, vaccination, home visits" },
  { id: "transport",   label: "Transport",         hi: "à¤ªà¤°à¤¿à¤µà¤¹à¤¨",         icon: "truck",
    hint: "Mandi pickup, cold storage" },
  { id: "labour",      label: "Labour",            hi: "à¤®à¤œà¤¼à¤¦à¥‚à¤°",          icon: "user",
    hint: "Daily wage workers, contract" },
  { id: "soil",        label: "Soil & Lab",        hi: "à¤®à¤¿à¤Ÿà¥à¤Ÿà¥€ à¤œà¤¾à¤à¤š",     icon: "field",
    hint: "Soil testing, water testing" },
  { id: "other",       label: "Other Service",     hi: "à¤…à¤¨à¥à¤¯ à¤¸à¥‡à¤µà¤¾",       icon: "tool",
    hint: "Something else" },
];

// Trending news + government schemes (mixed feed surfaced on Home)
const NEWS_SCHEMES = [
  {
    id: "n1", kind: "scheme",
    title: "PM-KISAN 17th instalment released",
    body: "â‚¹2,000 credited to over 9.3 crore farmers. Check status on pmkisan.gov.in",
    tag: "PM-KISAN", deadline: null, date: "2 days ago",
    source: "Ministry of Agriculture", accent: "#1F5A3A",
  },
  {
    id: "n2", kind: "news",
    title: "MSP for wheat raised to â‚¹2,425 / qtl",
    body: "Cabinet approves â‚¹150 hike for rabi 2026 marketing season.",
    tag: "MSP update", deadline: null, date: "Today",
    source: "Press Information Bureau", accent: "#B05E2E",
  },
  {
    id: "n3", kind: "scheme",
    title: "PMFBY enrolment closes Dec 15",
    body: "Crop insurance for rabi crops. â‚¹2/100 premium for food grains.",
    tag: "Crop Insurance", deadline: "Dec 15", date: "1 week ago",
    source: "PMFBY", accent: "#2E4A7F",
  },
  {
    id: "n4", kind: "scheme",
    title: "Drone Didi: 80% subsidy on agri drones",
    body: "Women SHGs get drones + training. Apply via Krishi Vigyan Kendra.",
    tag: "New scheme", deadline: "Mar 31", date: "5 days ago",
    source: "MoA & FW", accent: "#7A4F9E",
  },
  {
    id: "n5", kind: "news",
    title: "Heavy rain warning â€” Telangana, Oct 20â€“22",
    body: "IMD orange alert for Warangal, Karimnagar. Harvest standing crop early.",
    tag: "Weather alert", deadline: null, date: "1 hour ago",
    source: "IMD", accent: "#B05E2E",
  },
  {
    id: "n6", kind: "scheme",
    title: "Telangana: â‚¹10,000/ha drought relief",
    body: "Farmers in 22 mandals eligible. Apply at MeeSeva centre.",
    tag: "State scheme", deadline: "Nov 30", date: "3 days ago",
    source: "Govt of Telangana", accent: "#1F5A3A",
  },
];

const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "à¤¹à¤¿à¤¨à¥à¤¦à¥€" },
  { code: "te", name: "Telugu", native: "à°¤à±†à°²à±à°—à±" },
  { code: "kn", name: "Kannada", native: "à²•à²¨à³à²¨à²¡" },
  { code: "ta", name: "Tamil", native: "à®¤à®®à®¿à®´à¯" },
  { code: "ml", name: "Malayalam", native: "à´®à´²à´¯à´¾à´³à´‚" },
  { code: "mr", name: "Marathi", native: "à¤®à¤°à¤¾à¤ à¥€" },
  { code: "gu", name: "Gujarati", native: "àª—à«àªœàª°àª¾àª¤à«€" },
  { code: "bn", name: "Bengali", native: "à¦¬à¦¾à¦‚à¦²à¦¾" },
  { code: "or", name: "Odia", native: "à¬“à¬¡à¬¼à¬¿à¬†" },
  { code: "pa", name: "Punjabi", native: "à¨ªà©°à¨œà¨¾à¨¬à©€" },
  { code: "as", name: "Assamese", native: "à¦…à¦¸à¦®à§€à¦¯à¦¼à¦¾" },
];

const USERS = [
  { id: "u1", name: "Ramesh Yadav", phone: "9876543210", village: "Hanamkonda", district: "Warangal", state: "Telangana", crops: ["rice", "cotton"], listings: 4, joined: "Feb 2024" },
  { id: "u2", name: "Priya Patil", phone: "9988776655", village: "Niphad", district: "Nashik", state: "Maharashtra", crops: ["onion", "tomato", "grape"], listings: 7, joined: "Aug 2023" },
  { id: "u3", name: "Sukhwinder Singh", phone: "9123456789", village: "Khanna", district: "Ludhiana", state: "Punjab", crops: ["wheat", "rice"], listings: 12, joined: "Jan 2024" },
  { id: "u4", name: "Mahesh Reddy", phone: "9876512345", village: "Jangaon", district: "Warangal", state: "Telangana", crops: ["chili", "turmeric"], listings: 2, joined: "May 2024" },
  { id: "u5", name: "Lakshmi Devi", phone: "9988123456", village: "Mandya", district: "Mandya", state: "Karnataka", crops: ["sugarcane", "rice"], listings: 5, joined: "Mar 2024" },
  { id: "u6", name: "Vijay Borkar", phone: "9012345678", village: "Sangamner", district: "Pune", state: "Maharashtra", crops: ["soybean", "tomato"], listings: 3, joined: "Nov 2023" },
  { id: "me", name: "You", phone: "9876500000", village: "Hanamkonda", district: "Warangal", state: "Telangana", crops: ["rice", "cotton", "chili"], listings: 3, joined: "Jan 2026", isMe: true },
];

const LISTINGS = [
  {
    id: "l1", userId: "u1", category: "crop",
    title: "50 Quintal Sona Masoori Rice â€” Fresh Harvest",
    description: "Fresh harvest from October 2025. Stored in dry godown. Sortex cleaned. Sample available. Direct from farm, no middlemen.",
    price: 2280, priceUnit: "quintal", negotiable: true,
    quantity: "50 Quintals",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["crop photo Â· sona masoori", "godown view", "sortex sample"],
    tags: ["bulk", "fresh"], views: 124, inquiries: 8, posted: "2 days ago",
    available: "Available now",
  },
  {
    id: "l2", userId: "u3", category: "equipment",
    title: "Mahindra 575 DI Tractor for Hire â€” â‚¹650/hr",
    description: "Well-maintained Mahindra 575 DI (47HP). Available with operator. Can travel within 30km of Khanna. Implements available: rotavator, cultivator, plough.",
    price: 650, priceUnit: "hour", negotiable: false,
    quantity: "1 unit + operator",
    village: "Khanna", district: "Ludhiana", state: "Punjab",
    distance: 18,
    photos: ["tractor photo Â· mahindra 575", "implements"],
    tags: ["with operator"], views: 89, inquiries: 5, posted: "5 days ago",
    available: "Monâ€“Sat",
  },
  {
    id: "l3", userId: "u2", category: "crop",
    title: "Pukhraj Onion â€” Grade A, 20 Quintals",
    description: "Premium Pukhraj variety onions, Grade A. Harvested last week. Good shelf life. Buyer arranges transport from Niphad mandi.",
    price: 1850, priceUnit: "quintal", negotiable: true,
    quantity: "20 Quintals",
    village: "Niphad", district: "Nashik", state: "Maharashtra",
    distance: 6,
    photos: ["onion photo Â· pukhraj grade A", "storage"],
    tags: ["grade A", "fresh"], views: 67, inquiries: 4, posted: "1 day ago",
    available: "Available now",
  },
  {
    id: "l4", userId: "u4", category: "service",
    title: "Drone Spraying Service â€” â‚¹400/acre",
    description: "DJI Agras T30 drone spraying. Trained pilot. Pesticide and fertilizer spraying. Cover 1 acre in 8 minutes. Available across Warangal and Karimnagar.",
    price: 400, priceUnit: "acre", negotiable: false,
    quantity: "Available daily",
    village: "Jangaon", district: "Warangal", state: "Telangana",
    distance: 12,
    photos: ["drone photo Â· DJI T30", "field work"],
    tags: ["new tech"], views: 203, inquiries: 17, posted: "1 week ago",
    available: "Daily 6amâ€“6pm",
  },
  {
    id: "l5", userId: "u5", category: "input",
    title: "Organic Vermicompost â€” 50kg bags",
    description: "100% organic vermicompost from our own pits. Fully decomposed, weed-free. â‚¹450 per 50kg bag. Minimum 10 bags. Delivery within 25km.",
    price: 450, priceUnit: "bag (50kg)", negotiable: false,
    quantity: "200 bags available",
    village: "Mandya", district: "Mandya", state: "Karnataka",
    distance: 24,
    photos: ["vermicompost photo", "delivery vehicle"],
    tags: ["organic"], views: 45, inquiries: 3, posted: "3 days ago",
    available: "Available now",
  },
  {
    id: "l6", userId: "u6", category: "land",
    title: "3 Acres Irrigated Land â€” Lease â‚¹35,000/yr",
    description: "3 acres of fertile land near Sangamner. Borewell + drip irrigation. Suitable for tomato, onion, grapes. Lease minimum 2 years.",
    price: 35000, priceUnit: "acre/year", negotiable: true,
    quantity: "3 Acres",
    village: "Sangamner", district: "Pune", state: "Maharashtra",
    distance: 38,
    photos: ["land photo Â· 3 acre plot", "borewell", "drip system"],
    tags: ["irrigated", "long lease"], views: 156, inquiries: 12, posted: "2 weeks ago",
    available: "From June 2026",
  },
  {
    id: "l7", userId: "u1", category: "crop",
    title: "Cotton â€” 15 Quintals, MCU-5 Variety",
    description: "MCU-5 long staple cotton. Hand-picked. No moisture issues. From last week's picking.",
    price: 7200, priceUnit: "quintal", negotiable: true,
    quantity: "15 Quintals",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["cotton photo Â· MCU-5", "hand picked"],
    tags: ["hand-picked"], views: 78, inquiries: 6, posted: "4 days ago",
    available: "Available now",
  },
  {
    id: "l8", userId: "u3", category: "service",
    title: "Combine Harvester â€” Wheat & Rice",
    description: "John Deere W70 combine harvester. â‚¹2,200 per acre for wheat, â‚¹2,500 for rice. Operator included.",
    price: 2200, priceUnit: "acre", negotiable: false,
    quantity: "1 combine + operator",
    village: "Khanna", district: "Ludhiana", state: "Punjab",
    distance: 22,
    photos: ["combine photo Â· John Deere", "harvesting field"],
    tags: ["with operator", "seasonal"], views: 134, inquiries: 9, posted: "1 week ago",
    available: "Rabi season",
  },
  {
    id: "l9", userId: "u4", category: "crop",
    title: "Dry Red Chili â€” 8 Quintals, Teja Variety",
    description: "Teja variety dry red chili. High pungency. Sun-dried. Stored in clean godown.",
    price: 18500, priceUnit: "quintal", negotiable: true,
    quantity: "8 Quintals",
    village: "Jangaon", district: "Warangal", state: "Telangana",
    distance: 12,
    photos: ["chili photo Â· teja", "drying yard"],
    tags: ["sun-dried", "premium"], views: 92, inquiries: 7, posted: "3 days ago",
    available: "Available now",
  },
  {
    id: "l10", userId: "u2", category: "equipment",
    title: "5 HP Water Pump for Rent â€” â‚¹300/day",
    description: "Kirloskar 5HP diesel water pump. Self-priming. Includes 50ft suction hose. â‚¹300 per day, â‚¹1500 per week.",
    price: 300, priceUnit: "day", negotiable: false,
    quantity: "1 pump available",
    village: "Niphad", district: "Nashik", state: "Maharashtra",
    distance: 6,
    photos: ["pump photo Â· Kirloskar 5HP", "hose"],
    tags: ["with fuel"], views: 56, inquiries: 4, posted: "5 days ago",
    available: "Available now",
  },
  {
    id: "l11", userId: "u5", category: "service", subcategory: "veterinary",
    title: "Veterinary Visits â€” Buffalo & Cow",
    description: "Qualified vet, BVSc. Home visits â‚¹500. Vaccination, deworming, AI services. Mandya and surrounding villages.",
    price: 500, priceUnit: "visit", negotiable: false,
    quantity: "Daily appointments",
    village: "Mandya", district: "Mandya", state: "Karnataka",
    distance: 24,
    photos: ["vet photo Â· qualified vet"],
    tags: ["qualified"], views: 38, inquiries: 2, posted: "1 week ago",
    available: "Monâ€“Sat 8amâ€“6pm",
  },
  {
    id: "l12", userId: "u6", category: "input",
    title: "Hybrid Tomato Seeds â€” 1000 packets",
    description: "F1 Hybrid tomato seeds, disease resistant variety. Pack of 10g. Authorized distributor.",
    price: 180, priceUnit: "packet", negotiable: false,
    quantity: "1000 packets in stock",
    village: "Sangamner", district: "Pune", state: "Maharashtra",
    distance: 38,
    photos: ["seed packet photo Â· hybrid"],
    tags: ["F1 hybrid", "disease-resistant"], views: 41, inquiries: 3, posted: "6 days ago",
    available: "Year-round",
  },
  {
    id: "l13", userId: "u2", category: "livestock",
    title: "Murrah Buffalo â€” High Milk Yield (12L/day)",
    description: "3-year-old Murrah buffalo. Currently giving 12 litres per day. Second calving. Healthy, vaccinated.",
    price: 95000, priceUnit: "head", negotiable: true,
    quantity: "1 buffalo",
    village: "Niphad", district: "Nashik", state: "Maharashtra",
    distance: 6,
    photos: ["buffalo photo Â· murrah", "milk record"],
    tags: ["vaccinated", "high yield"], views: 112, inquiries: 9, posted: "3 days ago",
    available: "Available now",
  },
  {
    id: "l14", userId: "u4", category: "livestock",
    title: "Sirohi Goats â€” 8 Healthy, Ready for Sale",
    description: "8 Sirohi breed goats, 1â€“2 years old. Mix of male and female. All vaccinated. Good for dairy or meat.",
    price: 9500, priceUnit: "head", negotiable: true,
    quantity: "8 goats",
    village: "Jangaon", district: "Warangal", state: "Telangana",
    distance: 12,
    photos: ["goat photo Â· sirohi breed"],
    tags: ["vaccinated"], views: 68, inquiries: 5, posted: "5 days ago",
    available: "Available now",
  },
  {
    id: "l15", userId: "u3", category: "livestock",
    title: "Gir Cow â€” Pure Breed, A2 Milk",
    description: "Pure Gir breed cow, first calving. 8 litres per day. A2 quality milk. Healthy, dewormed.",
    price: 78000, priceUnit: "head", negotiable: true,
    quantity: "1 cow",
    village: "Khanna", district: "Ludhiana", state: "Punjab",
    distance: 22,
    photos: ["cow photo Â· gir breed"],
    tags: ["A2 milk", "pure breed"], views: 87, inquiries: 7, posted: "1 week ago",
    available: "Available now",
  },
  {
    id: "l16", userId: "u1", category: "service", subcategory: "veterinary",
    title: "Mobile Vet â€” AI & Vaccination, Warangal",
    description: "Mobile vet for artificial insemination, vaccination, and emergency calls. â‚¹400/visit + travel. Within 25 km.",
    price: 400, priceUnit: "visit", negotiable: false,
    quantity: "Daily 6amâ€“8pm",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["vet photo Â· mobile vet kit"],
    tags: ["mobile", "emergency"], views: 54, inquiries: 4, posted: "4 days ago",
    available: "Daily",
  },
];

// User's own listings â€” `kind` distinguishes sellable items from service offerings
const MY_LISTINGS = [
  {
    id: "m1", userId: "me", kind: "listing", category: "crop",
    title: "Rice â€” 30 Quintals, BPT 5204",
    description: "BPT 5204 variety. Fresh from October harvest. Available at farm gate.",
    price: 2100, priceUnit: "quintal", negotiable: true,
    quantity: "30 Quintals",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["crop photo Â· BPT 5204"],
    tags: ["fresh"], views: 142, inquiries: 8, orders: 3, posted: "1 day ago",
    available: "Available now",
    status: "active",
  },
  {
    id: "m2", userId: "me", kind: "service", category: "equipment", subcategory: "rental",
    title: "Rotavator for Rent â€” Sonalika",
    description: "Sonalika rotavator, 7ft. â‚¹450 per acre. Operator available.",
    price: 450, priceUnit: "acre", negotiable: false,
    quantity: "1 unit",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["rotavator photo"],
    tags: ["operator"], views: 86, inquiries: 4, orders: 6, posted: "1 week ago",
    available: "On request",
    rating: 4.7, ratingCount: 12,
    status: "active",
  },
  {
    id: "m4", userId: "me", kind: "listing", category: "input", subcategory: "seeds",
    title: "Cotton Seeds â€” BG-II, 25 packets",
    description: "BG-II cotton seeds, certified. 475g packets. Stored cool.",
    price: 850, priceUnit: "packet", negotiable: true,
    quantity: "25 packets",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["seed photo Â· cotton BG-II"],
    tags: ["certified"], views: 38, inquiries: 2, orders: 1, posted: "4 days ago",
    available: "Available now",
    status: "active",
  },
  {
    id: "m5", userId: "me", kind: "service", category: "service", subcategory: "spraying",
    title: "Drone Spraying â€” â‚¹400/acre",
    description: "DJI Agras T20. Trained pilot. Pesticide & fertilizer spraying. 1 acre in 8 min.",
    price: 400, priceUnit: "acre", negotiable: false,
    quantity: "Up to 40 acres/day",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["drone photo Â· spraying"],
    tags: ["pilot", "certified"], views: 211, inquiries: 11, orders: 9, posted: "2 weeks ago",
    available: "Monâ€“Sat",
    rating: 4.9, ratingCount: 24,
    status: "active",
  },
  {
    id: "m6", userId: "me", kind: "service", category: "service", subcategory: "veterinary",
    title: "Mobile Vet Visits â€” Buffalo & Cow",
    description: "BVSc qualified. AI, vaccination, deworming. Within 25 km of Hanamkonda.",
    price: 500, priceUnit: "visit", negotiable: false,
    quantity: "On call",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["vet photo"],
    tags: ["BVSc"], views: 64, inquiries: 5, orders: 4, posted: "3 weeks ago",
    available: "Daily",
    rating: 4.6, ratingCount: 9,
    status: "paused",
  },
  {
    id: "m3", userId: "me", kind: "listing", category: "crop",
    title: "Chili â€” 5 Quintals (Sold)",
    description: "Sold to local trader.",
    price: 17000, priceUnit: "quintal", negotiable: false,
    quantity: "5 Quintals",
    village: "Hanamkonda", district: "Warangal", state: "Telangana",
    distance: 0,
    photos: ["chili photo"],
    tags: [], views: 88, inquiries: 6, orders: 2, posted: "3 weeks ago",
    available: "Closed",
    status: "fulfilled",
  },
];

// Orders & service bookings against my items
// stage pipeline:  new  â†’  confirmed  â†’  in_progress  â†’  delivered  â†’  completed   (or "cancelled")
const ORDERS = [
  {
    id: "o1", kind: "order", listingId: "m1", listingTitle: "Rice â€” 30 Quintals, BPT 5204",
    buyerId: "u2", buyerName: "Priya Patil", buyerVillage: "Niphad, Nashik",
    qty: "20 Quintals", unitPrice: 2200, total: 44000,
    placed: "Today 9:50am", placedRel: "2 hr ago",
    stage: "new",
    payment: "advance pending", paymentPct: 0,
    notes: "Buyer asked for delivery to Nashik mandi.",
  },
  {
    id: "o2", kind: "order", listingId: "m1", listingTitle: "Rice â€” 30 Quintals, BPT 5204",
    buyerId: "u4", buyerName: "Mahesh Reddy", buyerVillage: "Jangaon, Warangal",
    qty: "10 Quintals", unitPrice: 2100, total: 21000,
    placed: "Today 11:45am", placedRel: "30 min ago",
    stage: "confirmed",
    payment: "50% advance", paymentPct: 50, advance: 10500,
    notes: "Pickup tomorrow 10am from farm gate.",
  },
  {
    id: "o3", kind: "booking", listingId: "m2", listingTitle: "Rotavator for Rent â€” Sonalika",
    buyerId: "u3", buyerName: "Sukhwinder Singh", buyerVillage: "Khanna, Ludhiana",
    qty: "8 acres", unitPrice: 450, total: 3600,
    placed: "Yesterday 3:00pm", placedRel: "1 day ago",
    stage: "in_progress",
    payment: "Pay on completion", paymentPct: 0,
    notes: "Booked for May 28â€“30. Operator confirmed.",
    scheduled: "May 28 Â· 7am",
  },
  {
    id: "o4", kind: "booking", listingId: "m5", listingTitle: "Drone Spraying â€” â‚¹400/acre",
    buyerId: "u6", buyerName: "Vijay Borkar", buyerVillage: "Sangamner, Pune",
    qty: "12 acres", unitPrice: 400, total: 4800,
    placed: "Yesterday 6:00pm", placedRel: "1 day ago",
    stage: "confirmed",
    payment: "Pay on completion", paymentPct: 0,
    notes: "Soybean field. Schedule before flowering.",
    scheduled: "May 24 Â· 6am",
  },
  {
    id: "o5", kind: "booking", listingId: "m5", listingTitle: "Drone Spraying â€” â‚¹400/acre",
    buyerId: "u4", buyerName: "Mahesh Reddy", buyerVillage: "Jangaon, Warangal",
    qty: "5 acres", unitPrice: 400, total: 2000,
    placed: "2 days ago", placedRel: "2 days ago",
    stage: "delivered",
    payment: "Paid in full", paymentPct: 100,
    notes: "Spraying complete. Awaiting acknowledgement.",
    scheduled: "May 19 Â· 6am",
  },
  {
    id: "o6", kind: "order", listingId: "m4", listingTitle: "Cotton Seeds â€” BG-II",
    buyerId: "u1", buyerName: "Ramesh Yadav", buyerVillage: "Hanamkonda, Warangal",
    qty: "5 packets", unitPrice: 850, total: 4250,
    placed: "3 days ago", placedRel: "3 days ago",
    stage: "completed",
    payment: "Paid in full", paymentPct: 100,
    notes: "Picked up from farm.",
  },
  {
    id: "o7", kind: "booking", listingId: "m6", listingTitle: "Mobile Vet Visits",
    buyerId: "u5", buyerName: "Lakshmi Devi", buyerVillage: "Mandya, Mandya",
    qty: "1 visit", unitPrice: 500, total: 500,
    placed: "1 week ago", placedRel: "1 week ago",
    stage: "completed",
    payment: "Paid in full", paymentPct: 100,
    notes: "AI for buffalo. Successful.",
  },
  {
    id: "o8", kind: "order", listingId: "m3", listingTitle: "Chili â€” 5 Quintals",
    buyerId: "u4", buyerName: "Mahesh Reddy", buyerVillage: "Jangaon, Warangal",
    qty: "5 Quintals", unitPrice: 17000, total: 85000,
    placed: "3 weeks ago", placedRel: "3 weeks ago",
    stage: "completed",
    payment: "Paid in full", paymentPct: 100,
    notes: "Trader pickup. Bulk transaction.",
  },
];

const MANDI_PRICES = [
  { commodity: "Rice", variety: "Sona Masoori", market: "Warangal Mandi", district: "Warangal", state: "Telangana", min: 2100, max: 2450, modal: 2280, unit: "Quintal", trend: 3.2, date: "2026-05-20", history: [2150, 2180, 2210, 2200, 2240, 2260, 2280] },
  { commodity: "Cotton", variety: "MCU-5", market: "Adilabad Mandi", district: "Adilabad", state: "Telangana", min: 6800, max: 7400, modal: 7100, unit: "Quintal", trend: -1.4, date: "2026-05-20", history: [7250, 7220, 7180, 7150, 7140, 7120, 7100] },
  { commodity: "Onion", variety: "Pukhraj", market: "Nashik Mandi", district: "Nashik", state: "Maharashtra", min: 1500, max: 2100, modal: 1850, unit: "Quintal", trend: 8.2, date: "2026-05-20", history: [1620, 1660, 1700, 1730, 1780, 1820, 1850] },
  { commodity: "Wheat", variety: "Lokwan", market: "Ludhiana Mandi", district: "Ludhiana", state: "Punjab", min: 2280, max: 2440, modal: 2350, unit: "Quintal", trend: 0.8, date: "2026-05-20", history: [2320, 2330, 2335, 2340, 2342, 2348, 2350] },
  { commodity: "Tomato", variety: "Hybrid", market: "Pune Mandi", district: "Pune", state: "Maharashtra", min: 1200, max: 2000, modal: 1600, unit: "Quintal", trend: -12.5, date: "2026-05-20", history: [1900, 1820, 1760, 1700, 1660, 1620, 1600] },
  { commodity: "Chili", variety: "Teja Dry", market: "Khammam Mandi", district: "Khammam", state: "Telangana", min: 17500, max: 19200, modal: 18500, unit: "Quintal", trend: 2.1, date: "2026-05-20", history: [18100, 18180, 18250, 18320, 18400, 18450, 18500] },
  { commodity: "Turmeric", variety: "Nizamabad", market: "Nizamabad Mandi", district: "Nizamabad", state: "Telangana", min: 13500, max: 14800, modal: 14200, unit: "Quintal", trend: 4.4, date: "2026-05-20", history: [13600, 13700, 13850, 13950, 14050, 14150, 14200] },
  { commodity: "Soybean", variety: "JS 335", market: "Latur Mandi", district: "Latur", state: "Maharashtra", min: 4400, max: 4800, modal: 4600, unit: "Quintal", trend: 1.2, date: "2026-05-20", history: [4540, 4560, 4570, 4580, 4585, 4590, 4600] },
];

const WEATHER = {
  location: "Hanamkonda, Warangal",
  current: {
    temp: 34,
    feelsLike: 38,
    condition: "Partly Cloudy",
    icon: "partly-cloudy",
    humidity: 62,
    wind: 14,
    rainProb: 20,
    uv: 7,
  },
  hourly: [
    { time: "Now", temp: 34, icon: "partly-cloudy", rain: 20 },
    { time: "12pm", temp: 36, icon: "sunny", rain: 10 },
    { time: "1pm", temp: 37, icon: "sunny", rain: 5 },
    { time: "2pm", temp: 37, icon: "sunny", rain: 5 },
    { time: "3pm", temp: 36, icon: "partly-cloudy", rain: 15 },
    { time: "4pm", temp: 35, icon: "partly-cloudy", rain: 30 },
    { time: "5pm", temp: 33, icon: "cloudy", rain: 50 },
    { time: "6pm", temp: 31, icon: "rain", rain: 70 },
    { time: "7pm", temp: 30, icon: "rain", rain: 65 },
    { time: "8pm", temp: 29, icon: "cloudy", rain: 40 },
  ],
  daily: [
    { day: "Tomorrow", date: "May 22", high: 36, low: 25, icon: "sunny", rain: 5 },
    { day: "Sat", date: "May 23", high: 35, low: 26, icon: "partly-cloudy", rain: 25 },
    { day: "Sun", date: "May 24", high: 32, low: 25, icon: "rain", rain: 80 },
    { day: "Mon", date: "May 25", high: 31, low: 24, icon: "rain", rain: 75 },
    { day: "Tue", date: "May 26", high: 33, low: 24, icon: "partly-cloudy", rain: 30 },
  ],
  advisory: [
    { type: "warn", title: "Heavy rain expected Sunday", text: "Delay sowing or harvesting between Sunday and Monday. Cover stored grain." },
    { type: "info", title: "Good day to spray", text: "Wind under 15 km/h today and tomorrow. Spray in early morning or evening." },
    { type: "tip", title: "Irrigate early morning", text: "High temperatures expected. Irrigate before 8am to reduce water loss." },
  ],
};

const INQUIRIES = [
  {
    id: "i1", listingId: "m1", listingTitle: "Rice â€” 30 Quintals, BPT 5204",
    fromUser: "u2", fromName: "Priya Patil", fromVillage: "Niphad, Nashik",
    type: "received", unread: 2,
    lastMessage: "Can you deliver to Nashik? I can pay extra for transport.",
    lastTime: "10 min ago",
    messages: [
      { from: "u2", body: "Namaste. I am interested in your rice. Is it still available?", time: "Yesterday 4:20pm" },
      { from: "me", body: "Yes, all 30 quintals available. Sample can be sent.", time: "Yesterday 5:10pm" },
      { from: "u2", body: "What is the lowest price you can give?", time: "Yesterday 5:14pm" },
      { from: "me", body: "â‚¹2200 per quintal, that is final. Direct from farm.", time: "Today 9:02am" },
      { from: "u2", body: "Can you deliver to Nashik? I can pay extra for transport.", time: "Today 9:50am" },
    ],
  },
  {
    id: "i2", listingId: "m1", listingTitle: "Rice â€” 30 Quintals, BPT 5204",
    fromUser: "u4", fromName: "Mahesh Reddy", fromVillage: "Jangaon, Warangal",
    type: "received", unread: 0,
    lastMessage: "OK I will visit your farm tomorrow morning around 10am.",
    lastTime: "2 hr ago",
    messages: [
      { from: "u4", body: "Brother, what is the rate?", time: "Today 11:00am" },
      { from: "me", body: "â‚¹2200 per quintal. Can send sample.", time: "Today 11:15am" },
      { from: "u4", body: "OK I will visit your farm tomorrow morning around 10am.", time: "Today 11:45am" },
    ],
  },
  {
    id: "i3", listingId: "m2", listingTitle: "Rotavator for Rent â€” Sonalika",
    fromUser: "u3", fromName: "Sukhwinder Singh", fromVillage: "Khanna, Ludhiana",
    type: "received", unread: 0,
    lastMessage: "Thank you, will book for next week.",
    lastTime: "1 day ago",
    messages: [
      { from: "u3", body: "Is rotavator available for 3 days from May 28?", time: "Yesterday 2:00pm" },
      { from: "me", body: "Yes, available. â‚¹450 per acre. How many acres?", time: "Yesterday 2:45pm" },
      { from: "u3", body: "Thank you, will book for next week.", time: "Yesterday 3:00pm" },
    ],
  },
  // sent
  {
    id: "i4", listingId: "l2", listingTitle: "Mahindra 575 DI Tractor for Hire",
    toUser: "u3", fromName: "Sukhwinder Singh", fromVillage: "Khanna, Ludhiana",
    type: "sent", unread: 1,
    lastMessage: "I can come on Monday morning. Is that OK?",
    lastTime: "30 min ago",
    messages: [
      { from: "me", body: "Hello, need tractor for 2 days. Rate?", time: "Today 8:30am" },
      { from: "u3", body: "â‚¹650/hr or â‚¹4500/day with operator. When you need?", time: "Today 9:00am" },
      { from: "me", body: "I can come on Monday morning. Is that OK?", time: "Today 11:00am" },
    ],
  },
  {
    id: "i5", listingId: "l5", listingTitle: "Organic Vermicompost â€” 50kg bags",
    toUser: "u5", fromName: "Lakshmi Devi", fromVillage: "Mandya, Mandya",
    type: "sent", unread: 0,
    lastMessage: "Sure, I will arrange transport from your village.",
    lastTime: "3 days ago",
    messages: [
      { from: "me", body: "Need 20 bags. Can you deliver to Warangal?", time: "3 days ago" },
      { from: "u5", body: "Distance is far. You arrange transport, I will load at our pit.", time: "3 days ago" },
      { from: "me", body: "Sure, I will arrange transport from your village.", time: "3 days ago" },
    ],
  },
];

const NOTIFICATIONS = [
  { id: "n1", type: "new_inquiry", title: "New inquiry on your rice", body: "Priya Patil from Nashik is interested", time: "10 min ago", group: "Today", unread: true, target: { tab: "profile", screen: "inquiries", id: "i1" } },
  { id: "n2", type: "inquiry_reply", title: "Sukhwinder Singh replied", body: "I can come on Monday morning. Is that OK?", time: "30 min ago", group: "Today", unread: true, target: { tab: "profile", screen: "inquiries", id: "i4" } },
  { id: "n3", type: "price_alert", title: "Rice prices up 3% in Warangal", body: "Modal price now â‚¹2,280/quintal", time: "4 hr ago", group: "Today", unread: true, target: { tab: "discover", screen: "prices" } },
  { id: "n4", type: "new_nearby_listing", title: "New listing near you", body: "Drone Spraying Service â‚¹400/acre Â· 12km away", time: "Yesterday 6:00pm", group: "Yesterday", unread: false, target: { tab: "browse", screen: "detail", id: "l4" } },
  { id: "n5", type: "listing_expiring", title: "Your rotavator listing expires in 3 days", body: "Renew now to keep it live", time: "Yesterday 9:00am", group: "Yesterday", unread: false, target: { tab: "profile", screen: "listings" } },
  { id: "n6", type: "price_alert", title: "Cotton prices dropped 1.4%", body: "Modal â‚¹7,100/quintal in Adilabad", time: "2 days ago", group: "Earlier", unread: false, target: { tab: "discover", screen: "prices" } },
  { id: "n7", type: "new_inquiry", title: "Mahesh Reddy inquired", body: "Brother, what is the rate?", time: "2 days ago", group: "Earlier", unread: false, target: { tab: "profile", screen: "inquiries", id: "i2" } },
];

export const AGRI_DATA = {
  STATES_DISTRICTS, CROPS, CATEGORIES, LISTING_CATEGORIES, SERVICE_TYPES, NEWS_SCHEMES, LANGUAGES,
  USERS, LISTINGS, MY_LISTINGS, ORDERS, MANDI_PRICES,
  WEATHER, INQUIRIES, NOTIFICATIONS,
};

